jobs:
  - name: puma-manifest
    type: manifest
    steps:
      - IN: puma-image
      - IN: puma-image-options
      - TASK: managed
  - name: deploy-to-staging-puma
    type: deploy
    steps:
      - IN: puma-manifest
      - IN: puma-image-params
      - IN: staging-cluster
      - IN: staging-loadbalancer
        applyTo:
          - manifest: puma-manifest
            image: puma-image
            port: 3000
      - TASK: managed
        deployMethod: upgrade
